version: "3"
services:
  server:
    build: ./server
    restart: on-failure
    command: sh -c "npm install && npm start"
    working_dir: /server
    ports:
      - 8000:8000

  client:
    build: ./client
    restart: on-failure
    command: sh -c "npm install && npm start"
    working_dir: /client
    ports:
      - 3000:3000