version: "3"
services:
  server:
    image: node:16-alpine
    restart: on-failure
    command: sh -c "cd server && npm install && npm start"
    working_dir: /server
    ports:
      - 8000:8000
    volumes:
      - ./:/server

  client:
    image: node:16-alpine
    restart: on-failure
    command: sh -c "cd client && npm install && npm start"
    working_dir: /client
    ports:
      - 3000:3000
    volumes:
      - ./:/client
